[package]
name = "axum-auth0-spruceid"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
openidconnect = { version = "3.4.0", default-features = false, features = ["reqwest"] }
tower-sessions = { version = "0.14.0", features = ["private"] }
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
uuid = { version = "1", features = ["v4"] }
serde = { version = "1.0.228", features = ["derive", "alloc"] }
serde_json = "1.0.145"
dotenv = "0.15"
sha2 = "0.10"
base64 = "0.21"
ssi = { version = "0.12", default-features = false, features = ["w3c", "ed25519"] }
