[package]
name = "axum-auth0-spruceid"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6", features = ["headers"] }
tokio = { version = "1", features = ["full"] }
openidconnect = { version = "3.4.0", default-features = false, features = ["reqwest"] }
axum-sessions = "0.6.1"
async-session = "3.0.0"
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
uuid = { version = "1", features = ["v4"] }
serde = { version = "1.0.228", features = ["derive", "alloc"] }
serde_json = "1.0.145"
dotenv = "0.15"
chrono = { version = "0.4", features = ["serde"] }
sha2 = "0.10"
base64 = "0.21"
